import numpy as np

# =====================================================================
# STUDENT IMPLEMENTATION (Group Theory & Cayley Graphs)
# =====================================================================

# ---------------------------------------------------------
# L1: Cayley Graph Generation
# ---------------------------------------------------------

def generate_cayley_graph(group, generators): #contains solution
    """
    L1: Generate the Cayley Graph using Breadth-First Search.
    Start at the identity.
    Multiply the current element by each generator on the right.
    Record the node and the directed edge (current_element, generator, new_element).
    Return (nodes, edges) where:
    - nodes is a set of unique GroupElements.
    - edges is a list of tuples: (source, generator, target).
      (generator should just be the string name of the generator e.g. 'a')
    """
    e = group.identity()
    nodes = set([e])
    edges = []
    
    queue = [e]
    visited = set([e])
    
    # Parse generator strings into GroupElements
    gen_elements = {g: group.parse(g) for g in generators}
    
    while queue:
        current = queue.pop(0)
        
        for g_str, g_elem in gen_elements.items():
            new_elem = current * g_elem
            edges.append((current, g_str, new_elem))
            
            if new_elem not in visited:
                visited.add(new_elem)
                nodes.add(new_elem)
                queue.append(new_elem)
                
    return nodes, edges

# ---------------------------------------------------------
# L2: Subgroups and Cosets
# ---------------------------------------------------------

def generate_subgroup(group, subset_strings): #contains solution
    """
    L2a: Given a list of generator strings (e.g. ['b']), compute the full 
    subgroup generated by them. This means closure under multiplication 
    and inversion.
    """
    e = group.identity()
    subgroup = set([e])
    queue = [e]
    
    gens = [group.parse(s) for s in subset_strings]
    # Add inverses for closure
    gens += [g.inv() for g in gens]
    
    while queue:
        current = queue.pop(0)
        for g in gens:
            new_elem = current * g
            if new_elem not in subgroup:
                subgroup.add(new_elem)
                queue.append(new_elem)
                
    return subgroup

def compute_left_cosets(group, subgroup_elements): #contains solution
    """
    L2b: Generate all Left Cosets of a subgroup.
    Return a list of sets, where each set is a coset (gH).
    """
    import networkx as nx
    H_graph = nx.Graph()
    all_elements = group.get_elements()
    H_graph.add_nodes_from(all_elements)
    
    for g in all_elements:
        for h in subgroup_elements:
            val = g * h
            if val in all_elements:  # Always true for finite groups
                H_graph.add_edge(g, val)
                
    # Left cosets are the connected components under right-multiplication by H
    cosets = [set(c) for c in nx.connected_components(H_graph)]
    
    # Ensure the subgroup (the coset containing identity) is always first!
    e = group.identity()
    subgroup_coset = next((c for c in cosets if e in c), set([e]))
    other_cosets = [c for c in cosets if e not in c]
    
    # Sort the other cosets for stability (by length and string rep)
    other_cosets.sort(key=lambda c: (len(c), min([str(x) for x in c])))
    
    return [subgroup_coset] + other_cosets

# ---------------------------------------------------------
# L3: Normality and Conjugacy
# ---------------------------------------------------------

def compute_conjugacy_class(group, element): #contains solution
    """
    L3a: Compute the conjugacy class of an element x: {g * x * g^-1 for all g in G}.
    """
    conj_class = set()
    all_elements = group.get_elements()
    for g in all_elements:
        val = g * element * g.inv()
        conj_class.add(val)
    return conj_class

def compute_normal_subgroups(group, list_of_subgroups): #contains solution
    """
    L3b: Given a list of subgroups (each is a set of GroupElements), 
    return a list of booleans indicating whether each is a normal subgroup.
    A subgroup H is normal if g * h * g^-1 in H for all g in G and h in H.
    """
    results = []
    all_elements = group.get_elements()
    for H in list_of_subgroups:
        is_normal = True
        for h in H:
            for g in all_elements:
                if (g * h * g.inv()) not in H:
                    is_normal = False
                    break
            if not is_normal: break
        results.append(is_normal)
    return results

# ---------------------------------------------------------
# L4: Center and Commutator
# ---------------------------------------------------------

def compute_center(group): #contains solution
    """
    L4a: Compute the Center Z(G) of the group.
    Z(G) = {z in G | z * g = g * z for all g in G}
    """
    center = set()
    all_elements = group.get_elements()
    for z in all_elements:
        commutes_with_all = True
        for g in all_elements:
            if z * g != g * z:
                commutes_with_all = False
                break
        if commutes_with_all:
            center.add(z)
    return center

def compute_commutator_subgroup(group): #contains solution
    """
    L4b: Compute the Commutator Subgroup [G, G].
    It is generated by all commutators [a, b] = a * b * a^-1 * b^-1.
    """
    commutators = set()
    all_elements = group.get_elements()
    for a in all_elements:
        for b in all_elements:
            val = a * b * a.inv() * b.inv()
            commutators.add(val)
            
    # The commutator subgroup is GENERATED BY the commutators
    # Since we have the elements as GroupElements, we can just run the closure algorithm
    e = group.identity()
    subgroup = set([e])
    queue = [e]
    gens = list(commutators)
    
    while queue:
        current = queue.pop(0)
        for g in gens:
            new_elem = current * g
            if new_elem not in subgroup:
                subgroup.add(new_elem)
                queue.append(new_elem)
                
    return subgroup


# =============================================================================
#  SELF-TESTING (add your own tests below)
# =============================================================================
if __name__ == '__main__':
    import unittest
    # Add your own unittest.TestCase classes here, then run:
    #     python implementation_tasks.py
    unittest.main(verbosity=2)
