"""Tests for group_problem implementation tasks."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import unittest
import implementation_tasks as tasks
import group_engine as ge


class TestLevel1Axioms(unittest.TestCase):
    def test_z4_passes(self):
        table = [[0,1,2,3],[1,2,3,0],[2,3,0,1],[3,0,1,2]]
        self.assertTrue(tasks.check_closure(table))
        self.assertTrue(tasks.check_associativity(table))
        self.assertEqual(tasks.find_identity(table), 0)
        self.assertTrue(tasks.check_inverses(table, 0))

    def test_broken_table_closure(self):
        table = [[0,1],[1,5]]  # 5 is not in {0,1}
        self.assertFalse(tasks.check_closure(table))

    def test_z6_mul_no_inverses(self):
        table = [[(i*j)%6 for j in range(6)] for i in range(6)]
        self.assertEqual(tasks.find_identity(table), 1)
        self.assertFalse(tasks.check_inverses(table, 1))  # 2, 3, 4 have no inverses


class TestLevel2Permutations(unittest.TestCase):
    def test_compose(self):
        p = [1, 2, 0]  # (0 1 2)
        q = [1, 0, 2]  # (0 1)
        r = tasks.compose_permutations(p, q)
        self.assertEqual(r, [2, 1, 0])  # p(q(i)): 0→1→2, 1→0→1, 2→2→0

    def test_inverse(self):
        p = [1, 2, 0]
        inv = tasks.inverse_permutation(p)
        identity = tasks.compose_permutations(p, inv)
        self.assertEqual(identity, [0, 1, 2])

    def test_order(self):
        p = [1, 2, 0]  # 3-cycle, order 3
        self.assertEqual(tasks.permutation_order(p), 3)
        self.assertEqual(tasks.permutation_order([0, 1, 2]), 1)

    def test_cycle_conversion(self):
        p = [1, 2, 0, 4, 3]
        cycles = tasks.one_line_to_cycles(p)
        self.assertEqual(len(cycles), 2)
        back = tasks.cycles_to_one_line(cycles, 5)
        self.assertEqual(back, p)

    def test_generate_group_cyclic(self):
        gens = [[1, 2, 0]]  # (0 1 2), generates Z3
        group = tasks.generate_permutation_group(gens, 3)
        self.assertEqual(len(group), 3)

    def test_generate_group_s3(self):
        gens = [[1, 2, 0], [1, 0, 2]]  # (0 1 2), (0 1) generate S3
        group = tasks.generate_permutation_group(gens, 3)
        self.assertEqual(len(group), 6)

    def test_parity(self):
        self.assertTrue(tasks.is_even_permutation([0, 1, 2]))  # identity
        self.assertFalse(tasks.is_even_permutation([1, 0, 2]))  # transposition
        self.assertTrue(tasks.is_even_permutation([1, 2, 0]))   # 3-cycle

class TestLevel3Cayley(unittest.TestCase):
    def test_z4(self):
        G = ge.from_Zn(4)
        nodes, edges = tasks.generate_cayley_graph(G, [1])
        self.assertEqual(len(nodes), 4)
        self.assertEqual(len(edges), 4)


class TestLevel4Subgroups(unittest.TestCase):
    def test_z6_subgroups(self):
        G = ge.from_Zn(6)
        sgs = tasks.find_all_subgroups(G)
        sizes = sorted(len(sg) for sg in sgs)
        self.assertEqual(sizes, [1, 2, 3, 6])  # divisors of 6

    def test_lagrange(self):
        G = ge.from_Dn(4)
        sgs = tasks.find_all_subgroups(G)
        for sg in sgs:
            self.assertEqual(G.order % len(sg), 0)


class TestLevel5Cosets(unittest.TestCase):
    def test_z6_cosets(self):
        G = ge.from_Zn(6)
        H = tasks.generate_subgroup(G, [2])  # <2> = {0, 2, 4}
        cosets = tasks.compute_left_cosets(G, H)
        self.assertEqual(len(cosets), 2)
        self.assertTrue(all(len(c) == 3 for c in cosets))

    def test_normal_in_abelian(self):
        G = ge.from_Zn(6)
        H = tasks.generate_subgroup(G, [2])
        self.assertTrue(tasks.is_normal(G, H))

    def test_non_normal_in_s3(self):
        G = ge.from_Sn(3)
        # subgroup generated by a transposition: {e, (0 1)} — not normal in S3
        # find index of (0 1)
        for i in range(G.order):
            if G.label(i) == '(0 1)':
                H = tasks.generate_subgroup(G, [i])
                self.assertEqual(len(H), 2)
                self.assertFalse(tasks.is_normal(G, H))
                break


class TestLevel6Center(unittest.TestCase):
    def test_abelian_center(self):
        G = ge.from_Zn(5)
        center = tasks.compute_center(G)
        self.assertEqual(len(center), 5)  # whole group

    def test_d4_center(self):
        G = ge.from_Dn(4)
        center = tasks.compute_center(G)
        self.assertEqual(len(center), 2)  # {e, r²}

    def test_conjugacy_classes_partition(self):
        G = ge.from_Dn(3)
        classes = tasks.compute_conjugacy_classes(G)
        total = sum(len(c) for c in classes)
        self.assertEqual(total, G.order)


class TestLevel7Homomorphisms(unittest.TestCase):
    def test_z6_to_z3(self):
        G = ge.from_Zn(6)
        H = ge.from_Zn(3)
        phi = [i % 3 for i in range(6)]
        self.assertTrue(tasks.is_homomorphism(G, H, phi))
        ker = tasks.compute_kernel(G, H, phi)
        self.assertEqual(len(ker), 2)  # {0, 3}
        img = tasks.compute_image(G, H, phi)
        self.assertEqual(len(img), 3)  # all of Z3

    def test_bad_homomorphism(self):
        G = ge.from_Zn(4)
        H = ge.from_Zn(3)
        phi = [0, 1, 2, 0]  # not a homomorphism
        self.assertFalse(tasks.is_homomorphism(G, H, phi))


class TestGroupEngine(unittest.TestCase):
    def test_zn(self):
        G = ge.from_Zn(5)
        self.assertEqual(G.order, 5)
        self.assertEqual(G.multiply(2, 3), 0)
        self.assertEqual(G.inverse(2), 3)

    def test_un(self):
        G = ge.from_Un(8)
        self.assertEqual(G.order, 4)  # {1, 3, 5, 7}

    def test_dn(self):
        G = ge.from_Dn(3)
        self.assertEqual(G.order, 6)

    def test_sn(self):
        G = ge.from_Sn(3)
        self.assertEqual(G.order, 6)

    def test_from_perms(self):
        # S3 from generators (0 1 2) and (0 1)
        gens = [(1, 2, 0), (1, 0, 2)]
        G = ge.from_permutation_generators(gens, 3)
        self.assertEqual(G.order, 6)

    def test_element_order(self):
        G = ge.from_Zn(6)
        self.assertEqual(G.element_order(0), 1)  # identity
        self.assertEqual(G.element_order(1), 6)  # generator
        self.assertEqual(G.element_order(2), 3)
        self.assertEqual(G.element_order(3), 2)


if __name__ == '__main__':
    unittest.main()
