import unittest
import numpy as np
import sys, os

base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if base_dir not in sys.path:
    sys.path.insert(0, base_dir)

import implementation_tasks as tasks

class TestLevel3(unittest.TestCase):
    def test_subgroup_generation(self):
        # Z4 = <a | aaaa=e>. Subgroup generated by a^2 is {e, aa}
        nodes = {"e", "a", "aa", "aaa"}
        subgroup = tasks.generate_subgroup({"aa"}, nodes, [("aaaa", "")])
        self.assertEqual(subgroup, {"e", "aa"})
        
    def test_cosets(self):
        # Z4. H = {e, aa}. Cosets: {e, aa}, {a, aaa}
        nodes = {"e", "a", "aa", "aaa"}
        cosets = tasks.compute_left_cosets({"e", "aa"}, nodes, [("aaaa", "")])
        self.assertEqual(len(cosets), 2)

if __name__ == '__main__':
    unittest.main()
